const products = [
  {
    id: 1,
    image: '/images/coffeemilk.png',
    title: 'Caffè Latte',
    description: 'Smooth espresso with steamed milk and a light layer of foam.',
    category: 'Coffee',
    subcategory: 'Milk Coffee',
    price: 4.5,
    rating: 4.7,
  },
  {
    id: 2,
    image: '/images/coffeemilk.png',
    title: 'Espresso',
    description: 'Strong and bold espresso shot with rich crema.',
    category: 'Coffee',
    subcategory: 'Black Coffee',
    price: 3.0,
    rating: 4.9,
  },
  {
    id: 3,
    image: '/images/coffeemilk.png',
    title: 'Cappuccino',
    description:
      'Espresso topped with steamed milk foam and a sprinkle of cocoa.',
    category: 'Coffee',
    subcategory: 'Milk',
    price: 4.8,
    rating: 4.6,
  },
  {
    id: 4,
    image: '/images/coffeemilk.png',
    title: 'Americano',
    description: 'Espresso diluted with hot water for a smooth, classic taste.',
    category: 'Coffee',
    subcategory: 'Black Coffee',
    price: 3.5,
    rating: 4.5,
  },
  {
    id: 5,
    image: '/images/coffeemilk.png',
    title: 'Ice Coffee',
    description: 'Chilled coffee served over ice with optional milk or syrup.',
    category: 'Coffee',
    subcategory: 'Cold',
    price: 5.0,
    rating: 4.8,
  },
  {
    id: 6,
    image: '/images/coffeemilk.png',
    title: 'Mocha',
    description: 'Espresso blended with chocolate and steamed milk.',
    category: 'Coffee',
    subcategory: 'Milk',
    price: 5.2,
    rating: 4.8,
  },
]
export default products
